### ISSUE TITLE
何をどういう風に管理するのか

### ISSUE THREAD

**Issue by IkezoeMakoto** [kizokukai/admin_users#1]

**Comment by IkezoeMakoto** [comment]
```
application/services/zoe.go [2:53 PM]
私の意見でいうと kizokukai.github.io の権限は緩くしておきたくて
admin_users を変えられる権限は管理者だけ持ってればよいのかなと

m-hirao.rs [2:53 PM]
ID・パスワードとかその辺の管理はAdminsみたいなプライベートリポジトリを作るって話？
ですねえ

nihei.rb [2:55 PM]
>ID・パスワードとかその辺の管理はAdminsみたいなプライベートリポジトリを作るって話？
それです。
admin_users：何のアカウントが誰が管理下に置いてるか
admins：そのアカウントたちのID/Pass（全ID/Passをkizokukai organizationが持つ）
みたいな (edited) 

紅の尾田 [2:57 PM]
アカウントって例えば？
twitterとかコンパスか

nihei.rb [2:58 PM]
そうそう

紅の尾田 [2:58 PM]
なるなる

m-hirao.rs [3:01 PM]
Connpassはグループページ見れば明らかなので明示する必要性を感じないですね…

application/services/zoe.go [3:02 PM]
一か所にまとまってたら管理するのは楽くらいっすかね

m-hirao.rs [3:03 PM]
そうすると
• GitHub Organizaiton
• twitter
• Facebook group
• kizokukai.org ドメインの管理
くらいですかね

application/services/zoe.go [3:03 PM]
例えば誰か管理者として増えた時に漏れを防げる

m-hirao.rs [3:04 PM]
イヤーでもよく考えると管理者になった瞬間に全部のサイトの管理情報のぞきに行けるのはなんか嫌な気がしてきたぞ
```

**Comment by GOD-oda** [comment]
ドメインなんだけど、俺の個人アカウントで買ってるからどうしましょ？

**Comment by IkezoeMakoto** [comment]
テスト

**Comment by GOD-oda** [comment]
```
m-hirao.rs [15:38]
event_mokumoku が event_lt と event_dev_camp と同列になるのが気持ち悪さある（ event_mokumoku_admin と event_lt と event_dev_camp が意味合い的にはイコールになるはず）
event_mokumoku_admin -> event_mokumoku
event_mokumoku -> event_mokumoku_work (working は20文字以内に収まらないためチャンネル名制限に引っかかる）

とかが正しいように見える

nihei.rb [15:40]
なるほど。

ShalinFragment.java [15:46]
管理ようのチャンネルは個人的には分けたい

m-hirao.rs [15:48]
意図が汲みにくいのでもう少し詳しく気持ちを書いてほしい

ShalinFragment.java [16:01]
当日の参加者がコミュニケーションをとるチャンネルと、
運営者のチャンネルを分けて管理したい、という意図です
Githubにて当日までの管理などをすること考えると、常時ログを残してあげる必要はあるのかな？って思ったりしてて
当日の内容とかは確かに残したい気持ちもわかるので、
admin_から始まる管理者用のチャンネルはログを残さない運用にしたいです
まあ最悪event_から始まるチャンネルは全部ログを残すようにしてもいいですが

m-hirao.rs [16:09]
当日参加者がコミュニケーション取るチャンネルと運営者のチャンネルは別管理されてたほうがいいっていのは賛成ですねえ（現状もくもく会だけそうなってる）
ちなみにログ残す方針は逆だなあという感覚があって、Adminとかで上がった議論とかが流されてイベントに反映されないとかのほうが困るので、Adminのほうが僕は残っててほしい。（当日参加の内容とかはアンケート収集で十分という考え）
ちなみに管理用のチャンネルは個人的に分けたいから読み取ったのは
• #dev_kizokukai はシステム管理的な話だけしたい
• なのでアカウント管理とか、チャンネル命名規則の話は別にチャンネルできる方がいいんじゃない？
ってことだと思ってました

ShalinFragment.java [16:13]
あー、そこは言葉足らずだった
申し訳ない
そしてAdminを残したい認識だったか
これは俺の理解不足
まぁたしかに今だともくもく会しか当日活用されないはずなので、チャンネル名はもう少し考える
```

**Comment by GOD-oda** [comment]
さて、結局チャンネルはどうしますかね？

**Comment by yumechi** [comment]
これでコメント流れるようになったっしょ（このコメントは後で消す）

**Comment by GOD-oda** [comment]
これどうします？

**Comment by IkezoeMakoto** [comment]
https://github.com/kizokukai/admin_users/issues/1#issuecomment-458009926

>ドメインなんだけど、俺の個人アカウントで買ってるからどうしましょ？

これは別issueで話しましょうか。別議題だと思うので

**Comment by 5hal1n** [comment]
とりあえず、prefixをまとめたく、
event_ ： イベント系
dev_ ： 開発系
この二つがついてるものはログを取るという運用方法にします。
雑談系でログを残したい場合はprefixとして_を先頭に付けてもらう運用方法にしようかと。
異議あれば今日中に。
なければこれで全体に告知します。

**Comment by 5hal1n** [comment]
また、Githubに残すかGoogleSSに残すかの部分だと、githubは認証通さないといけなく面倒なのでGoogleSSに残す形で運用しようと思います。

**Comment by IkezoeMakoto** [comment]
えーと、書いてくれてる内容はありがたいですし基本的に賛成です。

運用ルールについては決めて終わりではなく、細かく問題提起して解決していける環境づくりが大切なので、細かくイテレートしていきましょう。

ですが、ここのissueには今二つの議題が混じってしまっていて。

* 管理者の管理をどこで可視化するか
    * 背景 slackの名前とかを変えたいときに誰にお願いすればいいか不明
* slackのログが消える問題をどうするか

ということで一つ目の内容についても話したいと思っています

**Comment by 5hal1n** [comment]
そうですね、確かに混じっちゃってましたね。
２つ目のログ問題に関しては別にissueを切ってそっちでやり取りしましょう。

**Comment by IkezoeMakoto** [comment]
ログ問題はこちらで話しましょう

https://github.com/kizokukai/admin_users/issues/2

**Comment by GOD-oda** [comment]
connpassのアカウントだけど２つある
kizokukai_jpとkizokukai

**Comment by GOD-oda** [comment]
@here
これ早めに結論づけたい
https://github.com/kizokukai/admin_users/issues/1#issuecomment-458388591

**Comment by IkezoeMakoto** [comment]
## 何を
* slack の管理者
* github org の管理者
* connpass の管理者
* domain の管理者
* fb グループの管理者
* twitter アカウントの管理者

どのように、はこのレポジトリで管理するだろうし、いったん後回しで他何か検討するべきものありましたっけ？

**Comment by GOD-oda** [comment]
twitterかな

**Comment by IkezoeMakoto** [comment]
それもあった！(追記done

**Comment by GOD-oda** [comment]
connpassは２つアカウントある

**Comment by IkezoeMakoto** [comment]
これもぼちぼち進めないとっすね

とりあえず可視化だけでも進めますか

今週中に仮フォーマットでPRだそうかな

実際誰が管理者かとかは教えてもらって入れていこう

**Comment by 5hal1n** [comment]
・アカウントそのものを保有している
・アカウントに管理者が紐付いている
の2パターンがあるのね。
後者はパブリックに見せていいけど、
前者はプライベートにしないとだよね
あとは管理するものも違ってくると思った

**Comment by IkezoeMakoto** [comment]
あー、別にアカウントの管理(ID, pass)をここで管理したいという話ではなく、

誰に依頼したら、変更とかいろいろ対応してくれるかを明確にしたいというモチベーションだったので、 *誰* が大事かなと

**Comment by 5hal1n** [comment]
そうゆう話ではないのね
要は対応窓口を決めたいでおっけー？

**Comment by IkezoeMakoto** [comment]
yes!

**Comment by 5hal1n** [comment]
じゃあSlackで聞いて決めてしまおう。
ちょっとお酒飲んでるので今は対応難しい

**Comment by 5hal1n** [comment]
誰にどのアカウントを任せるか問題、
以下でいかがですか？？
### slack の管理者
@shalin-okada @yutonihei 
### github org の管理者
@IkezoeMakoto @shalin-okada 
### connpass の管理者
@Ushinji @n.meguro
### domain の管理者
@GOD-oda 
### fb グループの管理者
@sanolabs @shalin-okada 
### twitter アカウントの管理者
@GOD-oda @IkezoeMakoto @yumechi

**Comment by 5hal1n** [comment]
@GOD-oda @IkezoeMakoto @yumechi @sanolabs 
Connpassグループについて承諾が取れたらこれでいこうかと思うんですがいかがですか？

**Comment by IkezoeMakoto** [comment]
私は良いと思いますー

**Comment by 5hal1n** [comment]
全員から承諾取れたのでこれで進めます。
#generalでアナウンスするのでそれ用に文章とreadmeを用意します。
アナウンスまでしたらcloseします。

**Comment by yumechi** [comment]
> github org の管理者
> @IkezoeMakoto @shalin-okada

しれっと設定しました（元オーナーなので）

**Comment by yumechi** [comment]
Slack は @sanolabs が Primary Owner だから実は管理者から外せないよ

**Comment by yumechi** [comment]
> slack の管理者
> @shalin-okada @yutonihei

これもできたけど、僕を管理者から外せるのは Primary Owner の @sanolabs のみなので、頼んどいてください。

**Comment by yumechi** [comment]
あと GitHub Repository について、もともとイベント企画で動いてたチームが別プロジェクトになっているので、一部話に上がりましたが、LT、MokuMoku会のリポジトリはこちらの方で巻き取らせていただきました。

**Comment by IkezoeMakoto** [comment]
> 全員から承諾取れたのでこれで進めます。
> #generalでアナウンスするのでそれ用に文章とreadmeを用意します。
> アナウンスまでしたらcloseします。

進捗どうですか？

**Comment by 5hal1n** [comment]
進捗ありません！
今から30分で進捗作ります。

**Comment by 5hal1n** [comment]
@IkezoeMakoto 
https://github.com/kizokukai/admin_users
こんなんでいかがでしょうか？
slackには以下形で投げようかと

**Comment by 5hal1n** [comment]
```
@here
皆さんお疲れ様です。
今まで貴族会関連アカウントの管理者が不明瞭になってましたが、
今回貴族会メンバーの協力を経て、無事各管理者が決まりました。
GitHubのレポジトリにまとめてあるので、
各担当者や問い合わせ方法についてはそちらをご確認ください。
https://github.com/kizokukai/admin_users
```

**Comment by IkezoeMakoto** [comment]
> @IkezoeMakoto
> https://github.com/kizokukai/admin_users
> こんなんでいかがでしょうか？
> slackには以下形で投げようかと

README.mdに記載する形にしたんですね。よさそうです。ありがとうございます。
が、masterにコミットはやめてほしい、、次回からはブランチ切ってPR投げてください、、お願いします。。。



> ```
> @here
> 皆さんお疲れ様です。
> 今まで貴族会関連アカウントの管理者が不明瞭になってましたが、
> 今回貴族会メンバーの協力を経て、無事各管理者が決まりました。
> GitHubのレポジトリにまとめてあるので、
> 各担当者や問い合わせ方法についてはそちらをご確認ください。
> https://github.com/kizokukai/admin_users
> ```

いいと思います！ありがとうございます！

**Comment by 5hal1n** [comment]
PR気をつけます><(今後業務でやってしまいそうで怖い)

そしたらこれで投げます！
投げたらclose

**Comment by 5hal1n** [comment]
だん
