### ISSUE TITLE
Slackのログが残らない問題

### ISSUE THREAD

**Issue by 5hal1n** [kizokukai/admin_users#2]

**Comment by 5hal1n** [comment]
# 決まってること
## 接頭詞
- dev_ : 開発系
- event_ : イベント系
- _ : ログを残したい雑談チャット

## 運用方法
一日一回、夜中のアクティブが少ない時間にチャットのログをSSに追加する。
チャンネル毎にシートが用意され、次の日のログは前日のセルの下に追加される。
どのチャンネルをログに残すかは接頭詞で決めるので、そこはメンバーにちゃんとやってもらう。

**Comment by IkezoeMakoto** [comment]
これもとりあえず仕組み出来そうならこれで行ってみますかー

コードもレポジトリ管理されてれば問題なさそうだし

**Comment by IkezoeMakoto** [comment]
https://github.com/kizokukai/ExptSlackLog

すでに動き始めてくれてた。さすが

**Comment by 5hal1n** [comment]
https://github.com/kizokukai/ExptSlackLog/issues/1
こっちに移しますclose
