### ISSUE TITLE
kizokukai.orgドメインについて

### ISSUE THREAD

**Issue by GOD-oda** [kizokukai/admin_users#3]
現在、ムームードメインにて尾田の個人アカウントで`kizokukai.org`のドメインを購入している

管理体制をしっかりするなら、個人アカウントではないほうがよいと思われる

**Comment by IkezoeMakoto** [comment]
貴族会ドメインの管理はどうする？というよりどうしたい？って感じかなと思った。

もともと貴族会自体おだ氏とさの氏が立ち上げたものだし、ドメインも取ったのはおださんなので、おださんの意向次第かなと

貴族会管轄にするのであれば貴族会アカウント作ってアカウントからするようにするか、

貴族会からお金払っておださんに管理を委任してる形にするか

**Comment by GOD-oda** [comment]
結論を言うと、先が見えてない
というのもノリでやったから
で、これに関しては貴族会がと言うより自分がごにょごにょ自己満みたくやってたし今後も続けようと思ってる
だから、ドメインは俺が管理してる方向で今は良いと思う
今はアイデアないから何ともだけど、将来的にはなんかしらで収益化出来ないかなーって考えてる
そうしたら定例の費用をそこから出せばいいしね

**Comment by IkezoeMakoto** [comment]
よさそう

それならどのタイミングでその管理を移すべきか、みたいなのだけここで明確化しておくといいかもですね〜

収益が立ったら？収益たてられそうな何かを作るとき？

とか

**Comment by GOD-oda** [comment]
うーん、収益ってもなー
定例に毎回10人程度くるわけで、例えば一人当たり500円分はこれから出せるようになったら切り替えてもいいかなーとか
なのでこの場合だと月5000円の収益が出たら、というイメージかな

**Comment by 5hal1n** [comment]
多分今の段階だとこれ以上進む気もしないしclose
