### ISSUE TITLE
貴族会Gmailのアカウントどこにいった問題

### ISSUE THREAD

**Issue by 5hal1n** [kizokukai/admin_users#5]
貴族会のGmailがパスワード等紛失、
そして復活もできない状態。
Gmailに紐づいているアカウント等あったらわりとまずくね？って思ったりもする
@GOD-oda @sanolabs 助けて〜、ドラえも〜ん

**Comment by GOD-oda** [comment]
俺かなぁ

**Comment by GOD-oda** [comment]
![73D71F1D-31CC-4A44-BB69-0D00B0852E48](https://user-images.githubusercontent.com/14949022/54822320-1f22aa80-4ce8-11e9-9d97-79deba00c218.png)

**Comment by GOD-oda** [comment]
メアドってこれだよね？

**Comment by GOD-oda** [comment]
すまん、まじでパスわからんし、貴族会アカウントを除外していいか？

**Comment by 5hal1n** [comment]
こればっかしはどうしようもないし除外してしまおう
